version: "3.3"
services:

  consul:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/fake-service:v0.3.3
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "http://localhost:9091/v1,http://localhost:9091/v2"
      UPSTREAM_CALL: "true"
      MESSAGE: "Hello World"
      HTTP_CLIENT_KEEP_ALIVES: "false"
      NAME: web
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web_v1.json
      CENTRAL_CONFIG: "/central_config/web-defaults.hcl;/central_config/api-defaults.hcl;/central_config/api-v1-defaults.hcl;/central_config/api-v2-defaults.hcl;/central_config/api-router.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
    network_mode: "service:web"

  # Define api service and envoy sidecar proxy for version 1 of the service
  api_v1:
    image: nicholasjackson/fake-service:v0.3.3
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: api
      MESSAGE: "API V1"
      SERVER_TYPE: "http"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  api_proxy_v1:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/api_v1.json
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "api-v1"]
    network_mode: "service:api_v1"
  
  # Define api service and envoy sidecar proxy for version 2 of the service
  api_v2:
    image: nicholasjackson/fake-service:v0.3.3
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: api
      MESSAGE: "API V2"
      SERVER_TYPE: "http"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  api_proxy_v2:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/api_v2.json
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "api-v2"]
    network_mode: "service:api_v2"
  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
