version: "3.3"
services:

  consul:
    image: consul:1.6.0
    command: ["consul","agent","-config-file=/config/consul-single-dc.hcl","-config-dir=/config"]
    volumes:
      - "../consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  # Define web service and envoy sidecar proxy
  web:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: grpc://localhost:9091
      UPSTREAM_CALL: "true"
      MESSAGE: "Hello World"
      HTTP_CLIENT_KEEP_ALIVES: "false"
      NAME: web
      TIMING_50_PERCENTILE: 30ms
      TIMING_90_PERCENTILE: 60ms
      TIMING_99_PERCENTILE: 90ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 9090:9090
  web_envoy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/web_v1.hcl
      #      CENTRAL_CONFIG: "/central_config/web-defaults.hcl;/central_config/api-defaults.hcl;/central_config/cache-defaults.hcl;/central_config/payments-defaults.hcl;central_config/currency-defaults.hcl/central_config/global-defaults.hcl"
    volumes:
      - "./service_config:/config"
      - "./central_config:/central_config"
    command: ["consul", "connect", "envoy","-sidecar-for", "web-v1"]
    network_mode: "service:web"

  # Define api service and envoy sidecar proxy for version 1 of the service
  api:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: localhost:9090
      NAME: api
      MESSAGE: "API V1"
      SERVER_TYPE: "grpc"
      TRACING_ZIPKIN: "http://jaeger:9411"
      UPSTREAM_URIS: "http://localhost:9091, http://localhost:9092"
      TIMING_50_PERCENTILE: 10ms
      TIMING_90_PERCENTILE: 20ms
      TIMING_99_PERCENTILE: 25ms
      TIMING_VARIANCE: 10
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  api_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/api_v1.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "api-v1"]
    network_mode: "service:api"
  
  cache:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      MESSAGE: "Cache response"
      NAME: "cache"
      SERVER_TYPE: "http"
      TIMING_50_PERCENTILE: 1ms
      TIMING_90_PERCENTILE: 2ms
      TIMING_99_PERCENTILE: 3ms
      TIMING_VARIANCE: 10
      TRACING_ZIPKIN: "http://jaeger:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  cache_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/cache_v1.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "cache-v1"]
    network_mode: "service:cache"
  
  payments:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      UPSTREAM_URIS: "http://localhost:9091"
      MESSAGE: "Payments response"
      NAME: "payments"
      SERVER_TYPE: "http"
      TRACING_ZIPKIN: "http://jaeger:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  payments_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/payments_v2.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "payments-v2"]
    network_mode: "service:payments"
  
  currency:
    image: nicholasjackson/fake-service:v0.4.1
    environment:
      LISTEN_ADDR: 0.0.0.0:9090
      MESSAGE: "Currency response"
      NAME: "currency"
      SERVER_TYPE: "http"
      TRACING_ZIPKIN: "http://jaeger:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  currency_proxy:
    image: nicholasjackson/consul-envoy:v1.6.0-v0.10.0
    environment:
      CONSUL_HTTP_ADDR: 10.5.0.2:8500
      CONSUL_GRPC_ADDR: 10.5.0.2:8502
      SERVICE_CONFIG: /config/currency_v1.hcl
    volumes:
      - "./service_config:/config"
    command: ["consul", "connect", "envoy","-sidecar-for", "currency-v1"]
    network_mode: "service:currency"

# Tracing and Metrics  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    links:
      - prometheus-server:prometheus
    volumes:
      - "./grafana/config.ini:/etc/grafana/config.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9990:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

  jaeger:
    image: jaegertracing/all-in-one:1.13
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
  
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
